// prettier-ignore
/* eslint-disable */
// This file is autogenerated by tools/build.ts.
// Do not modify manually.
    
export enum CustomEntityTypes {
  Database = 'rubedo:database',
  Grave = 'lw:grave',
  Loot = 'lw:loot',
  Sit = 'lw:sit',
  FloatingText = 'f:t',
  FloatingTextNpc = 'f:t_npc',
}
