// prettier-ignore
/* eslint-disable */
// This file is autogenerated by script.
// Do not modify manually.
    
export enum Language {
  en_US = 'en_US',
  ru_RU = 'ru_RU',
  en_GB = 'en_GB',
  de_DE = 'de_DE',
  es_ES = 'es_ES',
  es_MX = 'es_MX',
  fr_FR = 'fr_FR',
  fr_CA = 'fr_CA',
  it_IT = 'it_IT',
  ja_JP = 'ja_JP',
  ko_KR = 'ko_KR',
  pt_BR = 'pt_BR',
  pt_PT = 'pt_PT',
  zh_CN = 'zh_CN',
  zh_TW = 'zh_TW',
  nl_NL = 'nl_NL',
  bg_BG = 'bg_BG',
  cs_CZ = 'cs_CZ',
  da_DK = 'da_DK',
  el_GR = 'el_GR',
  fi_FI = 'fi_FI',
  hu_HU = 'hu_HU',
  id_ID = 'id_ID',
  nb_NO = 'nb_NO',
  pl_PL = 'pl_PL',
  sk_SK = 'sk_SK',
  sv_SE = 'sv_SE',
  tr_TR = 'tr_TR',
  uk_UA = 'uk_UA',
}

export const IntlLanguage: Record<Language, string> = {
  [Language.en_US]: 'en-US',
  [Language.ru_RU]: 'ru-RU',
  [Language.en_GB]: 'en-GB',
  [Language.de_DE]: 'de-DE',
  [Language.es_ES]: 'es-ES',
  [Language.es_MX]: 'es-MX',
  [Language.fr_FR]: 'fr-FR',
  [Language.fr_CA]: 'fr-CA',
  [Language.it_IT]: 'it-IT',
  [Language.ja_JP]: 'ja-JP',
  [Language.ko_KR]: 'ko-KR',
  [Language.pt_BR]: 'pt-BR',
  [Language.pt_PT]: 'pt-PT',
  [Language.zh_CN]: 'zh-CN',
  [Language.zh_TW]: 'zh-TW',
  [Language.nl_NL]: 'nl-NL',
  [Language.bg_BG]: 'bg-BG',
  [Language.cs_CZ]: 'cs-CZ',
  [Language.da_DK]: 'da-DK',
  [Language.el_GR]: 'el-GR',
  [Language.fi_FI]: 'fi-FI',
  [Language.hu_HU]: 'hu-HU',
  [Language.id_ID]: 'id-ID',
  [Language.nb_NO]: 'nb-NO',
  [Language.pl_PL]: 'pl-PL',
  [Language.sk_SK]: 'sk-SK',
  [Language.sv_SE]: 'sv-SE',
  [Language.tr_TR]: 'tr-TR',
  [Language.uk_UA]: 'uk-UA'
}

export const supportedLanguages = [
  Language.en_US,
  Language.ru_RU,
]

export const consoleLang = Language.ru_RU

export const defaultLang = Language.ru_RU

